package store

// The dashboard's counts. They take the same filters as search, so they are
// built by the same code rather than generated by sqlc (ADR 0008).

import (
	"context"
	"slices"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
)

const (
	defaultTopLimit = 10
	maxTopLimit     = 100
	// A timeline picks its own interval only if the window is at most
	// autoIntervals of it long, and takes none it is more than maxIntervals
	// of.
	autoIntervals = 200
	maxIntervals  = 1440
)

// TopFields are the fields events may be counted by, as the API names them.
var TopFields = []string{"src_ip", "dst_ip", "user", "host", "event_type"}

// fieldColumns maps each of TopFields to the events column it counts on,
// and to the text a value is reported as. Alert rules group by some of them.
var fieldColumns = map[string]struct{ column, text string }{
	"src_ip":     {"src_ip", "host(src_ip)"},
	"dst_ip":     {"dst_ip", "host(dst_ip)"},
	"user":       {"user_name", "user_name"},
	"host":       {"host", "host"},
	"event_type": {"event_type", "event_type"},
}

type TopParams struct {
	EventFilter
	// Field is one of TopFields.
	Field string
	// Limit is how many values to return, 1 to 100. Zero means 10.
	Limit int
}

type TopValue struct {
	Value string
	Count int64
}

type Top struct {
	// From and To are the window counted.
	From, To time.Time
	// Values are the most frequent first, and in byte order when their
	// counts are equal.
	Values []TopValue
}

// Top counts the events scope may see by the value of one field, and
// returns the most frequent values. Events without a value aren't counted.
// Unusable parameters are reported as Search reports them.
func (r *EventRepo) Top(ctx context.Context, scope Scope, p TopParams) (Top, error) {
	field, ok := fieldColumns[p.Field]
	if !ok {
		return Top{}, invalidParam("field must be one of %s", strings.Join(TopFields, ", "))
	}
	limit := p.Limit
	switch {
	case limit == 0:
		limit = defaultTopLimit
	case limit < 1 || limit > maxTopLimit:
		return Top{}, invalidParam("limit must be an integer between 1 and %d", maxTopLimit)
	}
	q, err := resolveCount(p.scopedTo(scope), time.Now())
	if err != nil {
		return Top{}, err
	}

	args, arg := bind()
	conds := append(q.where(arg), field.column+" IS NOT NULL")
	sql := "SELECT " + field.text + " AS value, count(*) AS count\nFROM events\nWHERE " +
		strings.Join(conds, "\n  AND ") +
		"\nGROUP BY " + field.column +
		"\nORDER BY count(*) DESC, " + field.text + " COLLATE \"C\"\nLIMIT " + arg(limit)

	values, err := read(ctx, r.store, scope, "cannot count events", sql, *args, pgx.RowToStructByName[TopValue])
	if err != nil {
		return Top{}, err
	}
	return Top{From: q.from, To: q.to, Values: values}, nil
}

// interval is a width a timeline's buckets may have.
type interval struct {
	name  string
	width time.Duration
}

// intervals are shortest first. Each divides a day, so buckets start at the
// same times whatever the window.
var intervals = []interval{
	{"1m", time.Minute}, {"5m", 5 * time.Minute}, {"15m", 15 * time.Minute}, {"30m", 30 * time.Minute},
	{"1h", time.Hour}, {"3h", 3 * time.Hour}, {"6h", 6 * time.Hour}, {"12h", 12 * time.Hour},
	{"1d", 24 * time.Hour},
}

// TimelineIntervals names the widths a timeline's buckets may have, shortest
// first.
func TimelineIntervals() []string {
	names := make([]string, len(intervals))
	for i, iv := range intervals {
		names[i] = iv.name
	}
	return names
}

type TimelineParams struct {
	EventFilter
	// Interval is one of TimelineIntervals. Empty picks the shortest that
	// divides the window into at most 200 parts.
	Interval string
}

type Bucket struct {
	// Start is inclusive, and the bucket ends where the next one starts.
	Start time.Time
	Count int64
}

type Timeline struct {
	// From and To are the window counted.
	From, To time.Time
	// Interval is the width of every bucket.
	Interval string
	// Buckets cover the window in order, empty ones included. They start
	// on whole multiples of the interval since the Unix epoch, so the
	// first may start before From and the last may end after To, but they
	// count only events within the window. There can be one more of them
	// than the window has intervals.
	Buckets []Bucket
}

// Timeline counts the events scope may see in buckets of equal width.
// Unusable parameters are reported as Search reports them, and so is a
// window more than 1440 intervals long.
func (r *EventRepo) Timeline(ctx context.Context, scope Scope, p TimelineParams) (Timeline, error) {
	q, err := resolveCount(p.scopedTo(scope), time.Now())
	if err != nil {
		return Timeline{}, err
	}
	iv, first, n, err := pickInterval(p.Interval, q.from, q.to)
	if err != nil {
		return Timeline{}, err
	}

	// The origin is the first bucket's start, so Postgres and the buckets
	// below agree on where each one starts.
	args, arg := bind()
	conds := q.where(arg)
	sql := "SELECT date_bin(make_interval(secs => " + arg(iv.width.Seconds()) + "), ts, " + arg(first) + "::timestamptz) AS start, count(*) AS count" +
		"\nFROM events\nWHERE " + strings.Join(conds, "\n  AND ") +
		"\nGROUP BY 1"

	counted, err := read(ctx, r.store, scope, "cannot count events", sql, *args, pgx.RowToStructByName[Bucket])
	if err != nil {
		return Timeline{}, err
	}
	counts := make(map[int64]int64, len(counted))
	for _, b := range counted {
		counts[b.Start.UnixMicro()] = b.Count
	}

	tl := Timeline{From: q.from, To: q.to, Interval: iv.name, Buckets: make([]Bucket, n)}
	for i := range tl.Buckets {
		start := first.Add(time.Duration(i) * iv.width)
		tl.Buckets[i] = Bucket{Start: start, Count: counts[start.UnixMicro()]}
	}
	return tl, nil
}

// resolveCount checks a count's filter and resolves its window, which
// defaults to search's.
func resolveCount(f EventFilter, now time.Time) (eventQuery, error) {
	q, err := resolveFilter(f)
	if err != nil {
		return eventQuery{}, err
	}
	from, to := defaultWindow(now)
	if err := q.setWindow(from, to); err != nil {
		return eventQuery{}, err
	}
	return q, nil
}

// pickInterval returns the interval named, or the one to use when none is,
// with the start of the first bucket from from to to and how many buckets
// there are.
func pickInterval(name string, from, to time.Time) (iv interval, first time.Time, n int, err error) {
	// Sub saturates rather than overflowing, and the window isn't empty.
	window := to.Sub(from)
	parts := func(iv interval) time.Duration { return (window-1)/iv.width + 1 }

	if name == "" {
		// The longest interval is a day, and the window is at most
		// maxIntervals of it.
		iv = intervals[len(intervals)-1]
		if i := slices.IndexFunc(intervals, func(iv interval) bool { return parts(iv) <= autoIntervals }); i >= 0 {
			iv = intervals[i]
		}
		if parts(iv) > maxIntervals {
			return interval{}, time.Time{}, 0, invalidParam("from and to are more than %d days apart, too far for a timeline", maxIntervals)
		}
	} else {
		i := slices.IndexFunc(intervals, func(iv interval) bool { return iv.name == name })
		if i < 0 {
			return interval{}, time.Time{}, 0, invalidParam("interval must be one of %s", strings.Join(TimelineIntervals(), ", "))
		}
		iv = intervals[i]
		if parts(iv) > maxIntervals {
			return interval{}, time.Time{}, 0, invalidParam("from and to are more than %d intervals of %s apart; choose a longer interval or a shorter window", maxIntervals, name)
		}
	}

	// The window is at most 1440 days long, so this can't saturate.
	first = from.UTC().Truncate(iv.width)
	return iv, first, int((to.Sub(first)-1)/iv.width) + 1, nil
}
