package store

// Search is the one events query whose shape is decided at runtime, so it is
// built here by hand rather than generated by sqlc (ADR 0008). Every value
// goes in as a bind parameter; only fixed SQL fragments are concatenated.

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/netip"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/mairuu/loghub/backend/internal/platform/errors"
	"github.com/mairuu/loghub/backend/internal/platform/pg"
	"github.com/mairuu/loghub/backend/internal/store/gen"
)

const (
	defaultSearchLimit  = 50
	maxSearchLimit      = 1000
	defaultSearchWindow = 24 * time.Hour
	// searchAhead is how far past now the default window reaches. It matches
	// how far ahead the normalizer accepts an event time, so an event from a
	// sender whose clock runs fast is still found straight away.
	searchAhead = time.Hour
	// searchTimeout cancels a search that would hold a connection too long,
	// usually a free-text one over a wide window.
	searchTimeout = 10 * time.Second
)

type Order string

const (
	OrderDesc Order = "desc"
	OrderAsc  Order = "asc"
)

// EventFilter selects events. Zero values don't filter. Text is matched
// exactly, except Query.
type EventFilter struct {
	Tenant string
	// From is inclusive and To exclusive. A nil From means 24 hours before
	// now, and a nil To an hour after now.
	From, To *time.Time
	// Sources matches any of them.
	Sources     []string
	EventType   string
	Action      string
	SeverityMin *int
	SeverityMax *int
	SrcIP       string
	User        string
	Host        string
	// Tags must all be present.
	Tags []string
	// Query matches a substring of any string or number in raw, ignoring
	// case. Keys don't match.
	Query string
}

type SearchParams struct {
	EventFilter
	// Order is by event time. Empty means newest first.
	Order Order
	// Limit is the page size, 1 to 1000. Zero means 50.
	Limit int
	// Cursor is the NextCursor of the previous page. The other parameters
	// must be the ones that page was fetched with, except that From and To
	// may be left nil to reuse that page's window.
	Cursor string
}

// Event is a stored event.
type Event = gen.Event

type EventPage struct {
	Events []Event
	// NextCursor fetches the following page. Empty on the last page.
	NextCursor string
}

// Search returns one page of the events scope may see. Unusable parameters
// are reported as errors.Malformed, with code invalid_parameter or
// invalid_cursor and a message naming the API parameter.
func (r *EventRepo) Search(ctx context.Context, scope Scope, p SearchParams) (EventPage, error) {
	if !scope.Admin && strings.TrimSpace(p.Tenant) == "" {
		// Row-level security limits a viewer to their tenant anyway, but its
		// condition is an OR that Postgres can't use an index for.
		p.Tenant = scope.TenantID
	}
	q, err := resolveSearch(p, time.Now())
	if err != nil {
		return EventPage{}, err
	}
	sql, args := q.sql()

	var events []Event
	err = r.store.InScope(ctx, scope, func(s *Store) error {
		if _, err := s.db.Exec(ctx, "SELECT set_config('statement_timeout', $1, true)", strconv.FormatInt(searchTimeout.Milliseconds(), 10)); err != nil {
			return pg.Wrap(err, "cannot set search timeout")
		}
		rows, err := s.db.Query(ctx, sql, args...)
		if err != nil {
			return searchError(ctx, err)
		}
		events, err = pgx.CollectRows(rows, pgx.RowToStructByName[Event])
		if err != nil {
			return searchError(ctx, err)
		}
		return nil
	})
	if err != nil {
		return EventPage{}, err
	}

	page := EventPage{Events: events}
	if len(events) > q.limit {
		page.Events = events[:q.limit]
		page.NextCursor = q.cursorAfter(page.Events[q.limit-1])
	}
	return page, nil
}

func searchError(ctx context.Context, err error) error {
	var pgErr *pgconn.PgError
	if ctx.Err() == nil && errors.As(err, &pgErr) && pgErr.Code == "57014" { // query_canceled, by statement_timeout
		return errors.Unavailable("search_timeout",
			fmt.Sprintf("the search took longer than %s; narrow the time range or the free-text query", searchTimeout)).
			Wrapping(err)
	}
	return pg.Wrap(err, "cannot search events")
}

// searchQuery is a validated SearchParams with its defaults filled in.
type searchQuery struct {
	EventFilter
	srcIP    *netip.Addr
	from, to time.Time
	order    Order
	limit    int
	after    *cursor
	hash     string
}

func resolveSearch(p SearchParams, now time.Time) (*searchQuery, error) {
	q := &searchQuery{EventFilter: p.EventFilter, order: p.Order, limit: p.Limit}
	f := &q.EventFilter

	switch {
	case q.limit == 0:
		q.limit = defaultSearchLimit
	case q.limit < 1 || q.limit > maxSearchLimit:
		return nil, invalidParam("limit must be an integer between 1 and %d", maxSearchLimit)
	}
	switch q.order {
	case "":
		q.order = OrderDesc
	case OrderAsc, OrderDesc:
	default:
		return nil, invalidParam("order must be asc or desc")
	}

	for _, sev := range []struct {
		name  string
		value *int
	}{{"severity_min", f.SeverityMin}, {"severity_max", f.SeverityMax}} {
		if sev.value != nil && (*sev.value < 0 || *sev.value > 10) {
			return nil, invalidParam("%s must be between 0 and 10", sev.name)
		}
	}
	if f.SeverityMin != nil && f.SeverityMax != nil && *f.SeverityMin > *f.SeverityMax {
		return nil, invalidParam("severity_min must not be greater than severity_max")
	}

	// Checked before anything else touches the text: case mapping would
	// quietly replace invalid UTF-8.
	texts := [][2]string{
		{"tenant", f.Tenant}, {"event_type", f.EventType}, {"action", f.Action},
		{"user", f.User}, {"host", f.Host}, {"q", f.Query},
	}
	for _, s := range f.Sources {
		texts = append(texts, [2]string{"source", s})
	}
	for _, t := range f.Tags {
		texts = append(texts, [2]string{"tag", t})
	}
	for _, t := range texts {
		// Postgres refuses both, and would fail the query with a 500.
		if !utf8.ValidString(t[1]) || strings.ContainsRune(t[1], 0) {
			return nil, invalidParam("%s must be UTF-8 text without NUL characters", t[0])
		}
	}

	// Stored text is trimmed, and source and action are lowercase, so a
	// filter spelled any other way could never match.
	f.Tenant = strings.TrimSpace(f.Tenant)
	f.EventType = strings.TrimSpace(f.EventType)
	f.Action = strings.ToLower(strings.TrimSpace(f.Action))
	f.User = strings.TrimSpace(f.User)
	f.Host = strings.TrimSpace(f.Host)
	f.Sources = normalizeSet(f.Sources, strings.ToLower)
	f.Tags = normalizeSet(f.Tags, nil)

	if s := strings.TrimSpace(f.SrcIP); s != "" {
		addr, err := netip.ParseAddr(s)
		if err != nil {
			return nil, invalidParam("src_ip must be an IPv4 or IPv6 address")
		}
		addr = addr.Unmap().WithZone("")
		q.srcIP = &addr
	}
	q.hash = q.filterHash()

	q.from, q.to = now.Add(-defaultSearchWindow), now.Add(searchAhead)
	if p.Cursor != "" {
		c, err := decodeCursor(p.Cursor)
		if err != nil {
			return nil, err
		}
		if c.Filter != q.hash || !sameTime(f.From, c.From) || !sameTime(f.To, c.To) {
			return nil, errors.Malformed("invalid_cursor", "cursor was issued for different parameters; start again without it")
		}
		q.from, q.to, q.after = c.From, c.To, &c
	}
	if f.From != nil {
		q.from = *f.From
	}
	if f.To != nil {
		q.to = *f.To
	}
	if !q.from.Before(q.to) {
		return nil, invalidParam("from must be before to")
	}
	return q, nil
}

// normalizeSet trims, maps, drops empty values and duplicates, and sorts, so
// equivalent filters look the same to the cursor check.
func normalizeSet(values []string, mapping func(string) string) []string {
	var out []string
	for _, v := range values {
		if v = strings.TrimSpace(v); mapping != nil {
			v = mapping(v)
		}
		if v != "" {
			out = append(out, v)
		}
	}
	slices.Sort(out)
	return slices.Compact(out)
}

func invalidParam(format string, args ...any) error {
	return errors.Malformed("invalid_parameter", fmt.Sprintf(format, args...))
}

const eventColumns = `id, ts, received_at, tenant_id, source, vendor, product,
	event_type, event_subtype, severity, action, src_ip, src_port, dst_ip, dst_port,
	protocol, user_name, host, process, url, http_method, status_code, rule_name,
	rule_id, cloud_account_id, cloud_region, cloud_service, raw, tags`

func (q *searchQuery) sql() (string, []any) {
	var args []any
	arg := func(v any) string {
		args = append(args, v)
		return "$" + strconv.Itoa(len(args))
	}

	conds := []string{"ts >= " + arg(q.from), "ts < " + arg(q.to)}
	if q.Tenant != "" {
		conds = append(conds, "tenant_id = "+arg(q.Tenant))
	}
	if len(q.Sources) > 0 {
		conds = append(conds, "source = ANY("+arg(q.Sources)+")")
	}
	if q.EventType != "" {
		conds = append(conds, "event_type = "+arg(q.EventType))
	}
	if q.Action != "" {
		conds = append(conds, "action = "+arg(q.Action))
	}
	if q.SeverityMin != nil {
		conds = append(conds, "severity >= "+arg(*q.SeverityMin))
	}
	if q.SeverityMax != nil {
		conds = append(conds, "severity <= "+arg(*q.SeverityMax))
	}
	if q.srcIP != nil {
		conds = append(conds, "src_ip = "+arg(*q.srcIP))
	}
	if q.User != "" {
		conds = append(conds, "user_name = "+arg(q.User))
	}
	if q.Host != "" {
		conds = append(conds, "host = "+arg(q.Host))
	}
	if len(q.Tags) > 0 {
		conds = append(conds, "tags @> "+arg(q.Tags))
	}
	if q.Query != "" {
		pattern := arg("%" + likeEscaper.Replace(q.Query) + "%")
		if !escapedInJSON(q.Query) {
			// A cheap first pass. When the text needs no escaping in JSON,
			// any value containing it puts it in raw's text form too.
			conds = append(conds, "raw::text ILIKE "+pattern)
		}
		conds = append(conds, `EXISTS (
	SELECT 1 FROM jsonb_path_query(raw, 'strict $.**') AS v
	WHERE jsonb_typeof(v) IN ('string', 'number') AND v #>> '{}' ILIKE `+pattern+`)`)
	}

	dir, cmp := "DESC", "<"
	if q.order == OrderAsc {
		dir, cmp = "ASC", ">"
	}
	if q.after != nil {
		conds = append(conds, "(ts, id) "+cmp+" ("+arg(q.after.Ts)+", "+arg(q.after.ID)+")")
	}

	sql := "SELECT " + eventColumns + "\nFROM events\nWHERE " + strings.Join(conds, "\n  AND ") +
		"\nORDER BY ts " + dir + ", id " + dir +
		"\nLIMIT " + arg(q.limit+1)
	return sql, args
}

var likeEscaper = strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`)

// escapedInJSON reports whether JSON text would spell s differently: quotes,
// backslashes and control characters are escaped.
func escapedInJSON(s string) bool {
	return strings.ContainsFunc(s, func(r rune) bool { return r == '"' || r == '\\' || r < 0x20 })
}

// cursor is a position in a result, with what it was fetched with. It is
// opaque to clients, but not secret: a tampered one can only move within
// what the caller may already read.
type cursor struct {
	Version int       `json:"v"`
	From    time.Time `json:"from"`
	To      time.Time `json:"to"`
	Ts      time.Time `json:"ts"`
	ID      int64     `json:"id"`
	Filter  string    `json:"f"`
}

const cursorVersion = 1

func (q *searchQuery) cursorAfter(e Event) string {
	b, _ := json.Marshal(cursor{Version: cursorVersion, From: q.from, To: q.to, Ts: e.Ts, ID: e.ID, Filter: q.hash})
	return base64.RawURLEncoding.EncodeToString(b)
}

func decodeCursor(s string) (cursor, error) {
	var c cursor
	b, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil || json.Unmarshal(b, &c) != nil || c.Version != cursorVersion {
		return cursor{}, errors.Malformed("invalid_cursor", "cursor is not one this API issued")
	}
	return c, nil
}

// filterHash identifies everything a cursor must be reused with, except the
// window, which the cursor carries.
func (q *searchQuery) filterHash() string {
	var ip string
	if q.srcIP != nil {
		ip = q.srcIP.String()
	}
	b, _ := json.Marshal([]any{
		q.order, q.Tenant, q.Sources, q.EventType, q.Action, q.SeverityMin, q.SeverityMax,
		ip, q.User, q.Host, q.Tags, q.Query,
	})
	sum := sha256.Sum256(b)
	return base64.RawURLEncoding.EncodeToString(sum[:12])
}

func sameTime(explicit *time.Time, fromCursor time.Time) bool {
	return explicit == nil || explicit.Equal(fromCursor)
}
