/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether the service can reach its database. Used by the
         *     container healthcheck and by the `loghub healthcheck` subcommand,
         *     both of which read only the status code.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Exchanges an email and password for a bearer token. The response also
         *     carries the token's expiry and the caller's role and tenant, so a
         *     client never needs to decode the token.
         *
         *     A wrong password and an unknown email get the same
         *     `invalid_credentials`. The email is matched ignoring case. The body
         *     may be at most 64 KiB.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenants
         * @description The tenants the caller may read, ordered by ID: every tenant for an
         *     admin, and a viewer's own tenant for a viewer. These are the values
         *     the `tenant` filters accept.
         */
        get: operations["listTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a single event
         * @description Accepts one vendor event as JSON, normalizes it, and stores it. The
         *     event is committed before this call returns, so it is searchable
         *     immediately.
         *
         *     A body that is not a JSON object is answered with 400 `invalid_json`.
         *     An event that is JSON but cannot be stored is answered with 200, and
         *     `errors[0]` says why, as it would for a line of a batch. The body may
         *     be at most 1 MiB.
         *
         *     Caddy exposes this as `POST /ingest` at the edge, which is the form
         *     the sample senders use.
         *
         *     Ingest takes the ingest key or an admin's token, and both may write to
         *     any tenant, so the event names its own. A viewer's token is refused
         *     with 403 `permission_denied`.
         */
        post: operations["ingestEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of events as NDJSON
         * @description One JSON event per line. This is what the collector forwards after
         *     buffering syslog and file input, sending the ingest key.
         *
         *     A malformed or unmappable line does not fail the request: the response
         *     reports `accepted` and `rejected` counts with per-line detail. This is
         *     deliberate. The collector retries a 5xx, 408 or 429 from its disk
         *     buffer until it succeeds, and drops the whole batch on any other
         *     status. Failing a batch for one poison line would either stall the
         *     buffer behind it forever or throw away every good record with it. A
         *     non-2xx status here means the request was unusable as a whole, not that
         *     some records were bad.
         *
         *     The collector does not read the response, so the server also logs
         *     each request that had rejected records, with counts by code.
         *
         *     Blank lines are skipped and are not records. A line may be at most
         *     1 MiB, and the body at most 32 MiB.
         */
        post: operations["ingestBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a whole export file as NDJSON
         * @description Same wire format and same per-record error handling as the batch
         *     endpoint, for uploading a vendor export directly:
         *
         *     ```
         *     curl -H 'Content-Type: application/x-ndjson' \
         *          --data-binary @samples/json/aws_cloudtrail.ndjson \
         *          https://localhost/api/v1/ingest/file
         *     ```
         *
         *     `tenant` and `source` may be supplied as query parameters, and apply
         *     only to records that do not carry their own.
         *
         *     The example needs `-H "Authorization: Bearer $INGEST_TOKEN"` once
         *     `INGEST_TOKEN` is exported from `.env`, or an admin's token.
         */
        post: operations["ingestFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search events
         * @description Filtered, time-ordered list of normalized events.
         *
         *     Results are paged with an opaque cursor rather than an offset. Events
         *     arrive continuously, so an offset would shift under the reader between
         *     pages, showing duplicates and silently skipping rows. Pass the
         *     `next_cursor` from one response as `cursor` on the next request; its
         *     absence means there are no more results.
         *
         *     A cursor is tied to the filters it was produced with. Re-using one with
         *     different filters is rejected with `invalid_cursor` rather than
         *     silently paging through a different result set. `from` and `to` may be
         *     left out after the first page; the cursor remembers the window.
         *
         *     Any other unusable parameter is rejected with `invalid_parameter`. A
         *     search still running after 10 seconds, usually a free-text one over a
         *     wide window, is cancelled with 503 `search_timeout`.
         */
        get: operations["searchEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Most frequent values
         * @description Counts matching events by the value of one field, and returns the most
         *     frequent values. Events with no value for the field aren't counted.
         *     Values with the same count are in byte order.
         *
         *     Unusable parameters and timeouts are answered as search answers them.
         */
        get: operations["topValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events over time
         * @description Counts matching events in buckets of equal width, for a chart of the
         *     window.
         *
         *     Without `interval`, the shortest interval that divides the window
         *     into at most 200 parts is used: one minute for an hour, 15 minutes for
         *     a day, an hour for a week. A window more than 1440 intervals long is
         *     refused with `invalid_parameter`, so a day can be counted by the
         *     minute but not two.
         *
         *     Other unusable parameters and timeouts are answered as search answers
         *     them.
         */
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alert rules
         * @description Every rule the caller may read, oldest first.
         */
        get: operations["listAlertRules"];
        put?: never;
        /**
         * Create an alert rule
         * @description Adds a rule, which is evaluated from the next minute on. Only an admin
         *     may create one. Rules can't be changed or removed through the API.
         *
         *     A field the schema doesn't list is refused with `unknown_field` rather
         *     than ignored, since a misspelt filter would otherwise match more than
         *     intended. The body may be at most 64 KiB.
         */
        post: operations["createAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alerts
         * @description The newest alerts the caller may read, newest first.
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "unavailable";
        };
        LoginRequest: {
            /** @example viewer@demoa.local */
            email: string;
            password: string;
        };
        Session: {
            /** @description Send it as a bearer token, `Authorization: Bearer <token>`. */
            token: string;
            /**
             * Format: date-time
             * @description When the token stops being accepted.
             */
            expires_at: string;
            role: components["schemas"]["Role"];
            /**
             * @description The caller's tenant. Absent for an admin, who has none.
             * @example demoA
             */
            tenant?: string;
        };
        /**
         * @description `admin` reads every tenant and may ingest. `viewer` reads one tenant.
         * @enum {string}
         */
        Role: "admin" | "viewer";
        Tenant: {
            /**
             * @description What requests and events name the tenant by.
             * @example demoA
             */
            id: string;
            /**
             * @description A name for people to read.
             * @example Demo A
             */
            name: string;
        };
        TenantList: {
            items: components["schemas"]["Tenant"][];
        };
        /**
         * @description Source category. Closed set: the database rejects anything else, so an
         *     unrecognised source on ingest is a rejected record rather than a new
         *     category.
         * @enum {string}
         */
        Source: "firewall" | "network" | "crowdstrike" | "aws" | "m365" | "ad" | "api";
        /**
         * @description One vendor event, as the vendor emits it.
         *
         *     Only `tenant` is always required, and `source` is required unless the
         *     record is a syslog line. The properties below are hints the normalizer
         *     looks for; anything else is kept verbatim in `raw` and stays
         *     searchable through the free-text filter. Sending a field this list
         *     does not mention is normal and is not an error.
         *
         *     Some vendors spell things differently, and those spellings are
         *     understood: `ip` means `src_ip`, `user` means the user field, and a
         *     nested `cloud` object is flattened.
         *
         *     A record is rejected only when it cannot be stored: it is not a JSON
         *     object, its tenant is missing or does not exist, or its source is
         *     missing or not recognised. A hint whose value cannot be normalized,
         *     such as `"severity": "high"` or text longer than 2048 bytes, is left
         *     empty instead, and the event is tagged `invalid:<field>`. NUL
         *     characters and invalid UTF-8, which the database cannot hold, are
         *     replaced with U+FFFD wherever they appear.
         *
         *     `tenant` is required because neither credential that may ingest is
         *     bound to a tenant: the ingest key and an admin's token may both write
         *     to any of them.
         */
        IngestEvent: {
            /** @example demoA */
            tenant: string;
            /**
             * @description Matched against the known source categories, ignoring case. An
             *     unrecognised value rejects the record with `unknown_source`.
             *
             *     May be omitted when `message` holds a syslog line. The source is
             *     then `firewall` if the line has firewall key=value fields (`action`,
             *     `src`, `dst`, `spt`, `dpt`, `proto`, `policy`), and `network`
             *     otherwise.
             * @example ad
             */
            source?: string;
            /**
             * Format: date-time
             * @description Event time. When absent or unparseable, the syslog header time is
             *     used if the line has an RFC 5424 header, and otherwise the time of
             *     receipt.
             *
             *     A time more than the retention period in the past, or more than an
             *     hour in the future, is replaced with the time of receipt and the
             *     event is tagged `rebased:timestamp`. Otherwise the event would be
             *     deleted on arrival or stored ahead of the partitions that exist.
             */
            "@timestamp"?: string;
            event_type?: string;
            event_subtype?: string;
            severity?: number;
            /** @example deny */
            action?: string;
            user?: string;
            /** @description Understood as `src_ip`. */
            ip?: string;
            src_ip?: string;
            dst_ip?: string;
            /** Format: int32 */
            src_port?: number;
            /** Format: int32 */
            dst_port?: number;
            protocol?: string;
            host?: string;
            process?: string;
            url?: string;
            http_method?: string;
            /** Format: int32 */
            status_code?: number;
            rule_name?: string;
            rule_id?: string;
            vendor?: string;
            product?: string;
            cloud?: components["schemas"]["CloudContext"];
            /**
             * @description A raw syslog line. When `source` is absent, `firewall` or `network`,
             *     the line is parsed: an RFC 5424 or RFC 3164 header gives host,
             *     process and severity, and a key=value body gives the other fields.
             *     For any other source, `message` is kept in `raw` and not parsed.
             */
            message?: string;
            /**
             * @description The original vendor payload. When absent, the whole request body is
             *     kept as `raw`.
             */
            raw?: {
                [key: string]: unknown;
            };
            _tags?: string[];
        } & {
            [key: string]: unknown;
        };
        /** @description Cloud provider context. Present only when the event carries any of it. */
        CloudContext: {
            account_id?: string;
            region?: string;
            service?: string;
        };
        /**
         * @description What happened to the records in the request. `accepted + rejected`
         *     equals the number of records read.
         */
        IngestResult: {
            /**
             * Format: int32
             * @description Records normalized and stored.
             */
            accepted: number;
            /**
             * Format: int32
             * @description Records that could not be stored.
             */
            rejected: number;
            /**
             * @description Why records were rejected. Capped at 100 entries; `rejected` is
             *     always the true count.
             */
            errors?: components["schemas"]["IngestRejection"][];
        };
        IngestRejection: {
            /**
             * Format: int32
             * @description Zero-based position in the request: the line number in an NDJSON
             *     body, counting blank lines. Always 0 for a single event.
             */
            index: number;
            /**
             * @description Why the record was not stored:
             *
             *     - `invalid_json`: the line is not a JSON object.
             *     - `missing_tenant`, `invalid_tenant`, `unknown_tenant`: no tenant,
             *       one that is not a valid tenant ID, or one that does not exist.
             *     - `tenant_not_permitted`: the caller may not write to the
             *       record's tenant.
             *     - `missing_source`, `unknown_source`: no source on a record that
             *       is not a syslog line, or one outside the known categories.
             *     - `record_too_large`: the line is longer than 1 MiB.
             *     - `unstorable_event`: the database refused one of the record's
             *       values. The normalizer is meant to prevent this, so it points
             *       to a loghub bug worth reporting.
             * @example unknown_source
             */
            code: string;
            message: string;
        };
        /**
         * @description A stored event in the normalized schema. Fields absent from an event
         *     are omitted rather than returned as null.
         */
        Event: {
            /**
             * @description Opaque identifier, unique with `@timestamp`. A string rather than a
             *     number so it survives JSON parsers that lose precision past 2^53.
             * @example 8123
             */
            id?: string;
            /**
             * Format: date-time
             * @description When the event happened.
             */
            "@timestamp": string;
            /**
             * Format: date-time
             * @description When loghub received it. Later than `@timestamp` by the collection lag.
             */
            received_at: string;
            /** @example demoA */
            tenant: string;
            source: components["schemas"]["Source"];
            vendor?: string;
            product?: string;
            event_type?: string;
            event_subtype?: string;
            severity?: number;
            /**
             * @description Free text, not a closed set. Values seen in practice include
             *     allow, deny, create, delete, login, logout and alert.
             * @example deny
             */
            action?: string;
            /**
             * @description Source address. May be IPv4 or IPv6.
             * @example 203.0.113.77
             */
            src_ip?: string;
            /** Format: int32 */
            src_port?: number;
            /** @description Destination address. May be IPv4 or IPv6. */
            dst_ip?: string;
            /** Format: int32 */
            dst_port?: number;
            protocol?: string;
            user?: string;
            host?: string;
            process?: string;
            url?: string;
            http_method?: string;
            /** Format: int32 */
            status_code?: number;
            rule_name?: string;
            rule_id?: string;
            cloud?: components["schemas"]["CloudContext"];
            /**
             * @description The original payload, always a JSON object. An event that arrived
             *     as a syslog line is kept as `{"message": "<the line>"}`.
             *
             *     Stored as `jsonb`, so key order is not preserved and duplicate keys
             *     are dropped: this round-trips semantically, not byte for byte.
             */
            raw: {
                [key: string]: unknown;
            };
            /**
             * @description The sender's own tags, followed by tags the normalizer adds:
             *
             *     - `auth_success`, `auth_failure`: a login and whether it succeeded,
             *       recognised the same way for every source. Filter on these rather
             *       than on vendor event names.
             *     - `rebased:timestamp`: the sent time was outside the accepted
             *       window, so `@timestamp` is the time of receipt.
             *     - `invalid:<field>`: that field's value could not be normalized and
             *       was left empty. The original value is still in `raw`.
             * @example [
             *       "auth_failure"
             *     ]
             */
            _tags: string[];
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            /**
             * @description Pass as `cursor` to get the following page. Absent when this is the
             *     last page.
             */
            next_cursor?: string;
        };
        /**
         * @description An event field to count by: `src_ip`, `dst_ip`, `user`, `host` or
         *     `event_type`.
         * @example src_ip
         * @enum {string}
         */
        TopField: "src_ip" | "dst_ip" | "user" | "host" | "event_type";
        TopValueList: {
            field: components["schemas"]["TopField"];
            /**
             * Format: date-time
             * @description Start of the window counted, inclusive.
             */
            from: string;
            /**
             * Format: date-time
             * @description End of the window counted, exclusive.
             */
            to: string;
            /** @description The most frequent values, most frequent first. */
            items: components["schemas"]["TopValue"][];
        };
        TopValue: {
            /**
             * @description A value of the field, as search returns it.
             * @example 203.0.113.77
             */
            value: string;
            /**
             * Format: int64
             * @description How many matching events had this value.
             * @example 42
             */
            count: number;
        };
        /**
         * @description A bucket width: minutes (`m`), hours (`h`) or a day (`d`). Buckets
         *     start on whole multiples of the width in UTC, so days start at
         *     midnight UTC.
         * @example 15m
         * @enum {string}
         */
        TimelineInterval: "1m" | "5m" | "15m" | "30m" | "1h" | "3h" | "6h" | "12h" | "1d";
        Timeline: {
            /**
             * Format: date-time
             * @description Start of the window counted, inclusive.
             */
            from: string;
            /**
             * Format: date-time
             * @description End of the window counted, exclusive.
             */
            to: string;
            interval: components["schemas"]["TimelineInterval"];
            /**
             * @description Every bucket that overlaps the window, oldest first, empty ones
             *     included. The first may start before `from` and the last may end
             *     after `to`, but only events within the window are counted. So
             *     there may be one more bucket than the window has intervals.
             */
            buckets: components["schemas"]["TimelineBucket"][];
        };
        TimelineBucket: {
            /**
             * Format: date-time
             * @description Start of the bucket, inclusive. It ends where the next one starts.
             */
            start: string;
            /**
             * Format: int64
             * @description How many matching events fell in the bucket.
             * @example 17
             */
            count: number;
        };
        /**
         * @description The event field a rule counts by: `src_ip`, `dst_ip`, `user` or
         *     `host`. Events without a value for it are not counted.
         * @enum {string}
         */
        AlertGroupBy: "src_ip" | "dst_ip" | "user" | "host";
        /**
         * @description Fires when at least `threshold` events matching the filter, with the
         *     same value of `group_by`, fall within `window_minutes`. Every filter
         *     field that is set must match; `tags` must all be present on the event.
         *     Text is matched exactly, except `action`, which is matched ignoring
         *     case as it is stored lowercase.
         */
        NewAlertRule: {
            /**
             * @description The tenant whose events the rule watches.
             * @example demoA
             */
            tenant: string;
            /** @example Repeated failed logins from one address */
            name: string;
            source?: components["schemas"]["Source"];
            event_type?: string;
            /** @example login */
            action?: string;
            /** @description Only events with severity at or above this. Excludes events with no severity. */
            severity_min?: number;
            /**
             * @description Tags the event must all carry. `auth_failure` marks a failed login
             *     from any source.
             * @example [
             *       "auth_failure"
             *     ]
             */
            tags?: string[];
            group_by: components["schemas"]["AlertGroupBy"];
            /**
             * Format: int32
             * @description How many matching events in one group make an alert.
             * @example 5
             */
            threshold: number;
            /**
             * Format: int32
             * @example 5
             */
            window_minutes: number;
            /**
             * Format: int32
             * @description After an alert, how long the same group stays quiet, counted from
             *     the end of the alert's window. Defaults to `window_minutes`, so one
             *     burst raises one alert, and a burst that keeps going raises another
             *     once per window.
             */
            cooldown_minutes?: number;
            /**
             * Format: uri
             * @description An `http` or `https` URL that each of the rule's alerts is POSTed
             *     to, as an `Alert` JSON object. Delivery is best effort: a request
             *     that fails or takes longer than 5 seconds is logged and not
             *     retried, and the alert is listed either way.
             * @example https://hooks.example.com/loghub
             */
            webhook_url?: string;
        };
        /** @description A stored rule. Filter fields that aren't set are omitted. */
        AlertRule: {
            /**
             * @description Opaque identifier, a string for the same reason as an event's.
             * @example 12
             */
            id: string;
            /** @example demoA */
            tenant: string;
            name: string;
            source?: components["schemas"]["Source"];
            event_type?: string;
            action?: string;
            severity_min?: number;
            tags: string[];
            group_by: components["schemas"]["AlertGroupBy"];
            /** Format: int32 */
            threshold: number;
            /** Format: int32 */
            window_minutes: number;
            /** Format: int32 */
            cooldown_minutes: number;
            /**
             * @description Listed only to callers who may create rules for the tenant, since
             *     a webhook URL often carries a secret.
             */
            webhook_url?: string;
            /** Format: date-time */
            created_at: string;
        };
        AlertRuleList: {
            items: components["schemas"]["AlertRule"][];
        };
        /**
         * @description One firing of a rule: `count` matching events whose `group_by` field
         *     was `group_key` fell between `window_start` and `window_end`. This is
         *     also the body a rule's webhook receives.
         */
        Alert: {
            /** @example 301 */
            id: string;
            /** @example 12 */
            rule_id: string;
            /** @example Repeated failed logins from one address */
            rule_name: string;
            /** @example demoA */
            tenant: string;
            group_by: components["schemas"]["AlertGroupBy"];
            /**
             * @description The value the matching events shared, such as an address.
             * @example 203.0.113.77
             */
            group_key: string;
            /**
             * Format: int64
             * @description How many matching events the window held.
             * @example 5
             */
            count: number;
            /**
             * Format: date-time
             * @description Start of the window, inclusive.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description End of the window, exclusive.
             */
            window_end: string;
            /**
             * Format: date-time
             * @description When the alert was raised.
             */
            created_at: string;
        };
        AlertList: {
            items: components["schemas"]["Alert"][];
        };
        ErrorResponse: {
            /**
             * @description Stable, machine-readable. Match on this; `message` is for people
             *     and may be reworded at any time.
             * @example invalid_request
             */
            code: string;
            message: string;
            /** @description Also returned as the `X-Request-Id` header. */
            request_id?: string;
            /** @description Per-field failures. Present only on 422. */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @example severity */
            field: string;
            /** @example out_of_range */
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description The request could not be parsed or a parameter was unusable. */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "invalid_parameter",
                 *       "message": "limit must be an integer between 1 and 1000",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description No credential was sent (`authentication_required`), or the one sent is
         *     malformed, expired or not recognised (`invalid_token`).
         */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "invalid_token",
                 *       "message": "the token is invalid or has expired; sign in again",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The caller is signed in but may not do this (`permission_denied`), or
         *     named a tenant it may not read (`tenant_not_permitted`).
         */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "tenant_not_permitted",
                 *       "message": "you may not access tenant \"demoB\"",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request body exceeded the configured limit. */
        PayloadTooLarge: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "body_too_large",
                 *       "message": "request body exceeds 32 MiB",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The Content-Type is not one this endpoint accepts. */
        UnsupportedMediaType: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unsupported_media_type",
                 *       "message": "expected application/x-ndjson",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The request parsed, but one or more fields are unusable. This is the
         *     only status that carries `errors[]`.
         */
        UnprocessableEntity: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "invalid_request",
                 *       "message": "the request contains invalid fields",
                 *       "request_id": "01J9Z3K2QW8XM4P7",
                 *       "errors": [
                 *         {
                 *           "field": "severity",
                 *           "code": "out_of_range",
                 *           "message": "severity must be between 0 and 10"
                 *         },
                 *         {
                 *           "field": "@timestamp",
                 *           "code": "invalid_format",
                 *           "message": "expected an RFC 3339 timestamp"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Something failed on the server. The detail is in the logs; quote
         *     `request_id` when reporting it.
         */
        InternalError: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "internal_error",
                 *       "message": "an unexpected error occurred",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description A dependency, normally the database, is unreachable, or a search or
         *     count ran past its time limit (`search_timeout`). Retrying later may
         *     succeed.
         */
        ServiceUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "database_unavailable",
                 *       "message": "cannot reach the database",
                 *       "request_id": "01J9Z3K2QW8XM4P7"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Narrows results to one tenant the caller may read. An admin may read
         *     every tenant, and a viewer only their own. Naming a tenant outside
         *     that set is 403 `tenant_not_permitted`, not an empty page; a tenant
         *     within it that doesn't exist returns nothing.
         *
         *     Omitting it is always safe and is the common case — it returns
         *     everything the caller may see.
         * @example demoA
         */
        TenantFilter: string;
        /**
         * @description Only events at or after this time. Defaults to 24 hours ago.
         * @example 2025-08-20T00:00:00Z
         */
        From: string;
        /**
         * @description Only events strictly before this time. Defaults to an hour from now,
         *     the furthest ahead an event time is accepted, so an event from a
         *     sender whose clock runs fast still shows up.
         */
        To: string;
        /** @description Repeat to match any of several sources. */
        SourceFilter: components["schemas"]["Source"][];
        EventTypeFilter: string;
        /** @example deny */
        ActionFilter: string;
        /** @description Only events with severity at or above this. Excludes events with no severity. */
        SeverityMin: number;
        /** @description Only events with severity at or below this. Excludes events with no severity. */
        SeverityMax: number;
        /**
         * @description Exact source address match.
         * @example 203.0.113.77
         */
        SrcIpFilter: string;
        /** @description Exact match on the user associated with the event. */
        UserFilter: string;
        HostFilter: string;
        /** @description Repeat to require several tags; an event must carry all of them. */
        TagFilter: string[];
        /**
         * @description Free-text match against the original payload: any string or number
         *     value in `raw` that contains this text, ignoring case. Keys don't
         *     match. This is the slowest filter available, so narrow the time range
         *     with it.
         */
        Query: string;
        /** @description Maximum events to return. Defaults to 50. */
        Limit: number;
        /**
         * @description The `next_cursor` from a previous response. Opaque: its encoding is not
         *     part of this contract and may change between releases.
         */
        Cursor: string;
        /** @description Order by event time. Defaults to `desc`, newest first. */
        Order: "asc" | "desc";
        /** @description The field to count events by. */
        TopField: components["schemas"]["TopField"];
        /** @description Maximum values to return. Defaults to 10. */
        TopLimit: number;
        /**
         * @description The width of each bucket. Defaults to the shortest that divides the
         *     window into at most 200 parts.
         */
        TimelineInterval: components["schemas"]["TimelineInterval"];
        /** @description Maximum alerts to return. Defaults to 50. */
        AlertLimit: number;
    };
    requestBodies: never;
    headers: {
        /** @description Correlates this response with the server log line. */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "viewer@demoa.local",
                 *       "password": "the VIEWER_PASSWORD from .env"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The email and password don't match an account. */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "invalid_credentials",
                     *       "message": "email or password is incorrect",
                     *       "request_id": "01J9Z3K2QW8XM4P7"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestEvent"];
            };
        };
        responses: {
            /**
             * @description Processed. `accepted` is 1 when the event was stored; a rejected
             *     event reports why in `errors[0]`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {"tenant":"demoA","message":"<134>Aug 20 12:44:56 fw01 vendor=demo product=ngfw action=deny src=10.0.1.10 dst=8.8.8.8 spt=5353 dpt=53 proto=udp msg=DNS blocked policy=Block-DNS"}
                 *     {"tenant":"demoA","source":"api","event_type":"app_login_failed","user":"alice","ip":"203.0.113.7","@timestamp":"2025-08-20T07:20:00Z"}
                 */
                "application/x-ndjson": string;
            };
        };
        responses: {
            /** @description Batch processed; counts report how many records stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestFile: {
        parameters: {
            query?: {
                /**
                 * @description Default tenant for records that omit one. Like a record's own
                 *     tenant, it must be one the caller may write to, or those records
                 *     are rejected with `tenant_not_permitted`.
                 */
                tenant?: string;
                /** @description Default source for records that omit one. */
                source?: components["schemas"]["Source"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-ndjson": string;
            };
        };
        responses: {
            /** @description File processed; counts report how many records stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    searchEvents: {
        parameters: {
            query?: {
                /**
                 * @description Narrows results to one tenant the caller may read. An admin may read
                 *     every tenant, and a viewer only their own. Naming a tenant outside
                 *     that set is 403 `tenant_not_permitted`, not an empty page; a tenant
                 *     within it that doesn't exist returns nothing.
                 *
                 *     Omitting it is always safe and is the common case — it returns
                 *     everything the caller may see.
                 * @example demoA
                 */
                tenant?: components["parameters"]["TenantFilter"];
                /**
                 * @description Only events at or after this time. Defaults to 24 hours ago.
                 * @example 2025-08-20T00:00:00Z
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Only events strictly before this time. Defaults to an hour from now,
                 *     the furthest ahead an event time is accepted, so an event from a
                 *     sender whose clock runs fast still shows up.
                 */
                to?: components["parameters"]["To"];
                /** @description Repeat to match any of several sources. */
                source?: components["parameters"]["SourceFilter"];
                event_type?: components["parameters"]["EventTypeFilter"];
                /** @example deny */
                action?: components["parameters"]["ActionFilter"];
                /** @description Only events with severity at or above this. Excludes events with no severity. */
                severity_min?: components["parameters"]["SeverityMin"];
                /** @description Only events with severity at or below this. Excludes events with no severity. */
                severity_max?: components["parameters"]["SeverityMax"];
                /**
                 * @description Exact source address match.
                 * @example 203.0.113.77
                 */
                src_ip?: components["parameters"]["SrcIpFilter"];
                /** @description Exact match on the user associated with the event. */
                user?: components["parameters"]["UserFilter"];
                host?: components["parameters"]["HostFilter"];
                /** @description Repeat to require several tags; an event must carry all of them. */
                tag?: components["parameters"]["TagFilter"];
                /**
                 * @description Free-text match against the original payload: any string or number
                 *     value in `raw` that contains this text, ignoring case. Keys don't
                 *     match. This is the slowest filter available, so narrow the time range
                 *     with it.
                 */
                q?: components["parameters"]["Query"];
                /** @description Maximum events to return. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description The `next_cursor` from a previous response. Opaque: its encoding is not
                 *     part of this contract and may change between releases.
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Order by event time. Defaults to `desc`, newest first. */
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching events, newest first unless `order=asc`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    topValues: {
        parameters: {
            query: {
                /** @description The field to count events by. */
                field: components["parameters"]["TopField"];
                /** @description Maximum values to return. Defaults to 10. */
                limit?: components["parameters"]["TopLimit"];
                /**
                 * @description Narrows results to one tenant the caller may read. An admin may read
                 *     every tenant, and a viewer only their own. Naming a tenant outside
                 *     that set is 403 `tenant_not_permitted`, not an empty page; a tenant
                 *     within it that doesn't exist returns nothing.
                 *
                 *     Omitting it is always safe and is the common case — it returns
                 *     everything the caller may see.
                 * @example demoA
                 */
                tenant?: components["parameters"]["TenantFilter"];
                /**
                 * @description Only events at or after this time. Defaults to 24 hours ago.
                 * @example 2025-08-20T00:00:00Z
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Only events strictly before this time. Defaults to an hour from now,
                 *     the furthest ahead an event time is accepted, so an event from a
                 *     sender whose clock runs fast still shows up.
                 */
                to?: components["parameters"]["To"];
                /** @description Repeat to match any of several sources. */
                source?: components["parameters"]["SourceFilter"];
                event_type?: components["parameters"]["EventTypeFilter"];
                /** @example deny */
                action?: components["parameters"]["ActionFilter"];
                /** @description Only events with severity at or above this. Excludes events with no severity. */
                severity_min?: components["parameters"]["SeverityMin"];
                /** @description Only events with severity at or below this. Excludes events with no severity. */
                severity_max?: components["parameters"]["SeverityMax"];
                /**
                 * @description Exact source address match.
                 * @example 203.0.113.77
                 */
                src_ip?: components["parameters"]["SrcIpFilter"];
                /** @description Exact match on the user associated with the event. */
                user?: components["parameters"]["UserFilter"];
                host?: components["parameters"]["HostFilter"];
                /** @description Repeat to require several tags; an event must carry all of them. */
                tag?: components["parameters"]["TagFilter"];
                /**
                 * @description Free-text match against the original payload: any string or number
                 *     value in `raw` that contains this text, ignoring case. Keys don't
                 *     match. This is the slowest filter available, so narrow the time range
                 *     with it.
                 */
                q?: components["parameters"]["Query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most frequent values, most frequent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopValueList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    timeline: {
        parameters: {
            query?: {
                /**
                 * @description The width of each bucket. Defaults to the shortest that divides the
                 *     window into at most 200 parts.
                 */
                interval?: components["parameters"]["TimelineInterval"];
                /**
                 * @description Narrows results to one tenant the caller may read. An admin may read
                 *     every tenant, and a viewer only their own. Naming a tenant outside
                 *     that set is 403 `tenant_not_permitted`, not an empty page; a tenant
                 *     within it that doesn't exist returns nothing.
                 *
                 *     Omitting it is always safe and is the common case — it returns
                 *     everything the caller may see.
                 * @example demoA
                 */
                tenant?: components["parameters"]["TenantFilter"];
                /**
                 * @description Only events at or after this time. Defaults to 24 hours ago.
                 * @example 2025-08-20T00:00:00Z
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Only events strictly before this time. Defaults to an hour from now,
                 *     the furthest ahead an event time is accepted, so an event from a
                 *     sender whose clock runs fast still shows up.
                 */
                to?: components["parameters"]["To"];
                /** @description Repeat to match any of several sources. */
                source?: components["parameters"]["SourceFilter"];
                event_type?: components["parameters"]["EventTypeFilter"];
                /** @example deny */
                action?: components["parameters"]["ActionFilter"];
                /** @description Only events with severity at or above this. Excludes events with no severity. */
                severity_min?: components["parameters"]["SeverityMin"];
                /** @description Only events with severity at or below this. Excludes events with no severity. */
                severity_max?: components["parameters"]["SeverityMax"];
                /**
                 * @description Exact source address match.
                 * @example 203.0.113.77
                 */
                src_ip?: components["parameters"]["SrcIpFilter"];
                /** @description Exact match on the user associated with the event. */
                user?: components["parameters"]["UserFilter"];
                host?: components["parameters"]["HostFilter"];
                /** @description Repeat to require several tags; an event must carry all of them. */
                tag?: components["parameters"]["TagFilter"];
                /**
                 * @description Free-text match against the original payload: any string or number
                 *     value in `raw` that contains this text, ignoring case. Keys don't
                 *     match. This is the slowest filter available, so narrow the time range
                 *     with it.
                 */
                q?: components["parameters"]["Query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every bucket in the window, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAlertRules: {
        parameters: {
            query?: {
                /**
                 * @description Narrows results to one tenant the caller may read. An admin may read
                 *     every tenant, and a viewer only their own. Naming a tenant outside
                 *     that set is 403 `tenant_not_permitted`, not an empty page; a tenant
                 *     within it that doesn't exist returns nothing.
                 *
                 *     Omitting it is always safe and is the common case — it returns
                 *     everything the caller may see.
                 * @example demoA
                 */
                tenant?: components["parameters"]["TenantFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "tenant": "demoA",
                 *       "name": "Repeated failed logins from one address",
                 *       "tags": [
                 *         "auth_failure"
                 *       ],
                 *       "group_by": "src_ip",
                 *       "threshold": 5,
                 *       "window_minutes": 5
                 *     }
                 */
                "application/json": components["schemas"]["NewAlertRule"];
            };
        };
        responses: {
            /** @description The rule as stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                /**
                 * @description Narrows results to one tenant the caller may read. An admin may read
                 *     every tenant, and a viewer only their own. Naming a tenant outside
                 *     that set is 403 `tenant_not_permitted`, not an empty page; a tenant
                 *     within it that doesn't exist returns nothing.
                 *
                 *     Omitting it is always safe and is the common case — it returns
                 *     everything the caller may see.
                 * @example demoA
                 */
                tenant?: components["parameters"]["TenantFilter"];
                /** @description Maximum alerts to return. Defaults to 50. */
                limit?: components["parameters"]["AlertLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The alerts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
